module: CoreDataPlus
author: Alessandro Marzoli
author_url: http://www.tinrobots.org
github_url: https://github.com/tinrobots/coredataplus
copyright: "©[Alessandro Marzoli](http://www.alessandromarzoli.com)"
clean: true
podspec: CoreDataPlus.podspec
