module: CoreDataPlus
author: Alessandro Marzoli
author_url: http://www.alessandromarzoli.com
github_url: http://www.alessandromarzoli.com/CoreDataPlus/
copyright: "©[Alessandro Marzoli](http://www.alessandromarzoli.com)"
clean: true
podspec: CoreDataPlus.podspec
