name: "CoreDataPlus CI"

on: 
  push:
    branches:
      - master

env:
    DEVELOPER_DIR: /Applications/Xcode_11.app

jobs:
  info:
    name: Show macOS and Xcode versions
    runs-on: macOS-latest    
    steps:
      - name: stats
        run: |
          sw_vers
          xcodebuild -version
          xcodebuild -showsdks
  macOS:
    name: Test macOS 
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1    
      - name: macOS
        run: xcodebuild -project "CoreDataPlus.xcodeproj" -scheme "CoreDataPlus macOS" -destination "platform=macOS" clean test
  iOS:
    name: Test iOS 
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["OS=13.0,name=iPhone 11", "OS=12.4,name=iPhone XS"]
    steps:
      - uses: actions/checkout@v1            
      - name: iOS - ${{ matrix.destination }}
        run: xcodebuild -project "CoreDataPlus.xcodeproj" -scheme "CoreDataPlus iOS" -destination "${{ matrix.destination }}" clean test
  tvOS:
    name: Test tvOS 
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["OS=13.0,name=Apple TV 4K (at 1080p)", "OS=12.4,name=Apple TV 4K"]
    steps:
      - uses: actions/checkout@v1            
      - name: tvOS - ${{ matrix.destination }}
        run: xcodebuild -project "CoreDataPlus.xcodeproj" -scheme "CoreDataPlus tvOS" -destination "${{ matrix.destination }}" clean test
  watchOS:
    name: Build watchOS
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["OS=6.0,name=Apple Watch Series 5 - 44mm", "OS=5.3,name=Apple Watch Series 4 - 44mm"]
    steps:
      - uses: actions/checkout@v1
      - name: watchOS - ${{ matrix.destination }}
        run: xcodebuild -project "CoreDataPlus.xcodeproj" -scheme "CoreDataPlus watchOS" -destination "${{ matrix.destination }}" clean build
  spm:
    name: Test SPM Integration
    runs-on: macOS-latest    
    needs: [macOS]
    steps:
      - uses: actions/checkout@v1
      - name: SPM Build & Test
        run: |
          swift build -Xswiftc -target -Xswiftc x86_64-apple-macosx10.13
          swift test -Xswiftc -target -Xswiftc x86_64-apple-macosx10.13

